image: go1.3
git:
  path: github.com/npateriya/drone-docker
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - find . 
publish:
  docker: 
    dockerfile: ./Dockerfile
    docker_host: 172.17.42.1:2375
    docker_port: 2375
    docker_version: 1.4.1
    registry_login: true
    username: npateriyainsecure
    password: githubpassword
    email: npateriya@yahoo.com
    image_name: npateriyainsecure/drone
    push_latest: true
